server:
  port: 8080

spring:
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379

JWTKey: DevKey12
EmailPassword: ${emailPassword}

autocomplete:
  limit: 10
  suffix: "_suffix"
  key: "autocomplete"
  score-key: "autocomplete:score"

logging:
  level:
    org:
      springframework: DEBUG