spring:
  data:
    redis:
      host: redis
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false

JWTKey: DevKey12
EmailPassword: uagpjpblfgzpklch

autocomplete:
  limit: 10
  suffix: "_suffix"
  key: "autocomplete"
  score-key: "autocomplete:score"

logging:
  level:
    org:
      springframework:
        r2bc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true